### ISSUE TITLE
Video orientation

### ISSUE THREAD

**Issue by KyrychenkoOleksandr** [begeekmyfriend/yasea#238]
As far as I understand, in onMetaData() method in RtmpConnextion class we sends initial data about video width, height, ect. But after rotation we don't update this data and server expects from us video in old resolution.
How can we update this data after rotation?
Thak you.

**Comment by begeekmyfriend** [comment]
The metadata packet is only to be sent on RTMP connection. I decide not to do re-connection operation in `onConfigurationChanged()` in `MainActivity.java` since quick re-connection might well fail with socket exceptions. And therefore the metadata does not need to be updated on rotation changed. In fact, even though the video size is to be set in metadata some players would neglect it and detect the size in other ways.
