### ISSUE TITLE
wowza rtmpConnect username/password help?

### ISSUE THREAD

**Issue by pisgocom** [begeekmyfriend/yasea#254]
WOWZA rtmpConnect username/password help?

Thank you

**Comment by begeekmyfriend** [comment]
Yasea does not support server specific authentication.

**Comment by begeekmyfriend** [comment]
See #212

**Comment by pisgocom** [comment]
rtmp://your_server_ip:1935/live?token=MY_TOKEN/streamName
I solved it by the above method.
Thank you.

**Comment by oantajames** [comment]
Hy @begeekmyfriend 
I really appreciate all your hard work and congrats you for YASEA.
I am trying to obtain what @pisgocom asked.
I research today and saw that on ffmpeg this is relativle not that hard. But since YASEA is not based on ffmpeg and has a pure java approach I think different things need to be modified. 
Do you have some suggestion's  on how to do this ? or where to look at ? 
Thank you!
