### ISSUE TITLE
回音以及噪音的问题

### ISSUE THREAD

**Issue by tz-xiaomage** [begeekmyfriend/yasea#29]
不知道能不能降低噪音以及回音？

**Comment by begeekmyfriend** [comment]
这个要用专门技术了，比如webrtc，没研究过

**Comment by banketree** [comment]
你可以参考下sip 开源项目   里面有对噪音处理

**Comment by begeekmyfriend** [comment]
[sipdroid](https://github.com/i-p-tel/sipdroid/tree/release-0.9), in pure Java, awesome!

**Comment by tz-xiaomage** [comment]
@banketree @begeekmyfriend 谢谢

**Comment by begeekmyfriend** [comment]
试了一下sipdroid，它的这个降噪需要在播放器那边进行相应解码才能配合使用，必须提供一致性，所以yasea不做了。

**Comment by begeekmyfriend** [comment]
The new version of flash player has integrated AEC(speex). See this [article](http://www.adobe.com/devnet/flashplayer/articles/acoustic-echo-cancellation.html) or this [sample code](http://www.adobe.com/cn/devnet/flashplayer/articles/acoustic-echo-cancellation.html). The problem is how to set the relevant options in RTMP packet.
