### ISSUE TITLE
hi 作者，请问你遇到过在SRS（http://www.ossrs.net/players/srs_player.html#） 上播放时，有回音的问题吗？

### ISSUE THREAD

**Issue by g123x** [begeekmyfriend/yasea#38]

**Comment by begeekmyfriend** [comment]
See #29

**Comment by g123x** [comment]
thanks your quick response so much

**Comment by g123x** [comment]
当网速好的时候，听不到回音。

**Comment by begeekmyfriend** [comment]
The new version of flash player has integrated AEC(speex). See this [article](http://www.adobe.com/cn/devnet/flashplayer/articles/acoustic-echo-cancellation.html) or this [sample code](http://mrbinitie.blogspot.sg/2011/03/implementing-acoustic-echo-suppression.html). The problem is how to set the relevant options in RTMP packet.
