### ISSUE TITLE
Delay Streaming

### ISSUE THREAD

**Issue by jokopitoyo** [begeekmyfriend/yasea#61]
Hello,

Can you add feature ignore packet out offdate to reduce buffer

TIA

**Comment by begeekmyfriend** [comment]
The largest frame number of video cache is limited to the [size of GOP](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/java/net/ossrs/yasea/SrsEncoder.java#L262) (in Yasea it is only 48 frames otherwise it will not be sent into the encoder). Since the FPS is 24, therefore the time delay can not be over 2 seconds.

The cache means frames cached from encoder (included) to RTMP socket.

You'd better check the server or the player.

**Comment by jokopitoyo** [comment]
Good, this what i mean..., i will try reduce cache player...
